config/routes.rb
Rails.application.routes.draw do
    #get 'welcome/index'
  devise_for :users
  #root :to => 'posts#index'
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # the followed are routes for the user_controller
  get "all_users", to: "users#all_users", as: "all_users"
  patch "/users/:id/like", to: "users#follow", as: "follow"
  #get "/users/:id/dashboard", to: "users#dashboard", as: "user_dashboard"
  patch "/posts/:id/adds", to: "posts#adds", as: "adds"
  post "/posts/add_category", to: "posts#add_category", as: "add_category"
  delete "/users/:id/unadds", to: "users#unadds", as: "unadds"
  delete "/users/:id/unlike", to: "users#unfollow", as: "unfollow"
  get "/users/:id/dashboard", to: "users#dashboard", as: "user_dashboard"
  get "/users/:id/profile", to: "users#profile", as: "user_profile"

  # the routes for category_controller
  get "/categories", to: "categories#index", as: "categories"
  get "/categories/:id", to: "categories#show", as: "category"
  post "/categories", to: "categories#create", as: "create_category"
  patch "/category/:id", to: "categories#update", as: "update_category"
  delete "/category/:id", to: "categories#destroy", as: "destroy_category"


  root :to => 'welcome#index'
end

app/models/post.rb
class Post < ApplicationRecord
    has_one_attached :image
    belongs_to :category, optional: true
    belongs_to :user, optional: true
    has_many :adds
    has_many :users_added, through: :adds, source: :user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @posts = @posts.where(user_id: params[:user_id]) if params[:user_id].present?
    @posts = @posts.where("content like '%#{params[:query]}%'") if params[:query].present?
    @posts = @posts.where(category: params[:category]) if params[:category].present?
    @posts = @posts.page(params[:page]).per(10)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  def adds
    @post = Post.find(params[:id]) 
    @adds = Add.create(user: current_user, post: @post)
    flash[:success] = "You have successfully add post ##{params[:id]}"
    redirect_to request.referer
  end
  # GET /posts/1/edit
  def edit
    if @post.user != current_user
      flash[:error] = 'Cannot edit other user\'s posts'
      redirect_to root_path
    end
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { 
          flash[:success] = 'Post was successfully created.'
          redirect_to @post 
        }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_category
    @post = params[:post]
    @post.category = params[:category]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:caption, :content, :category_id, :image, :user_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
    def flash_class(level)
        level = level.to_sym
        if level == :notice
            "alert alert-info"
        elsif level == :success
            "alert alert-success"
        elsif level == :error
            "alert alert-danger"
        else
            "alert alert-warning"
        end
    end

    def is_followed(fan, star)
        Follow.find_by(follower: fan, followed: star).present?
    end

    def is_added(post, user)
        Add.find_by(post: post, user: user).present?
    end
end

app/views/posts/_form.html.erb
<%= form_with(model: post, remote: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group new-post-field">
    <span class="input-group-addon h5" id="basic-addon1">Caption</span>
    <%= form.text_field :caption, class: "form-control h5" %>
  </div>

  <div class="input-group new-post-field">
    <span class="input-group-addon h5" id="basic-addon1">Content</span>
    <%= form.text_area :content, class: "form-control h5", id: "content-form" %>
  </div>

  <div>
    <%= form.text_field :category_id, class: "form-control hidden h5", id: "content-form" %>
  </div>

  <div class="new-post-field img-div">
    <span class="input-group-addon h5" id="basic-addon1">Choose File</span>
    <%= form.file_field :image, accept: "image/png,image/gif,image/jpeg", class: "form-control file-upload h5" %>
  </div>

  <div class="category-list">
    <%= link_to "#", method: :post, class: "btn btn-success none-btn category-btn h6", remote: true do %>
        None
    <% end %>
    <% current_user.categories.each do |c| %>
      <%= link_to "#", method: :post, class: "btn btn-success category-btn h6", id: c.id, remote: true do %>
        <%= c.name %>
      <% end %>
    <% end %> 
  </div>

  <div class="actions">
    <%= form.button :submit, class: 'btn btn-primary h6' %>
  </div>
<% end %>

<hr>
<h4> Cannot find the category you need? Click the button below to add a category </h4>

<button class="btn btn-primary h6" data-toggle="modal" data-target="#exampleModal">New Category</button>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title h5" id="exampleModalLabel">New Category</h4>
      </div>
      <div class="modal-body">
        <%= form_with(url: '/categories', method: :post, remote: true) do |form| %>
          <div class="input-group row">
            <div class="col-xs-8">
            <%= form.text_field :name, class: "form-control h5", placeholder: "Search for..." %>
            </div>
            <div class="col-xs-2">
            <button type="button" class="btn btn-default h6" data-dismiss="modal">Close</button>
            </div>
            <div class="col-xs-2">
            <%= form.button :submit, class: 'btn btn-primary submit-btn h6' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<style>
  .new-post-field {
    margin-bottom: 12px;
  }
  .category-list {
    margin-bottom: 10px;
  }
  .category-btn {
    background-color: grey;
    border-color: grey;
    color: white;
  }
  .none-btn {
    background-color: #5cb85c;
    border-color: #5cb85c;
    color: white;
  }
  .img-preview {
    margin-top: 7px;
  }
  form_main {
    width: 100%;
}
.form_main h4 {
    font-family: roboto;
    font-size: 20px;
    font-weight: 300;
    margin-bottom: 15px;
    margin-top: 20px;
    text-transform: uppercase;
}
.heading {
    border-bottom: 1px solid #fcab0e;
    padding-bottom: 9px;
    position: relative;
}
.heading span {
    background: #9e6600 none repeat scroll 0 0;
    bottom: -2px;
    height: 3px;
    left: 0;
    position: absolute;
    width: 75px;
}   
.form {
    border-radius: 7px;
    padding: 6px;
}
.txt[type="text"] {
    border: 1px solid #ccc;
    margin: 10px 0;
    padding: 10px 0 10px 5px;
    width: 100%;
}
.txt_3[type="text"] {
    margin: 10px 0 0;
    padding: 10px 0 10px 5px;
    width: 100%;
}
.txt2[type="submit"] {
    background: #242424 none repeat scroll 0 0;
    border: 1px solid #4f5c04;
    border-radius: 25px;
    color: #fff;
    font-size: 16px;
    font-style: normal;
    line-height: 35px;
    margin: 10px 0;
    padding: 0;
    text-transform: uppercase;
    width: 30%;
}
.txt2:hover {
    background: rgba(0, 0, 0, 0) none repeat scroll 0 0;
    color: #5793ef;
    transition: all 0.5s ease 0s;
}
  .h6{
  margin-top: 2rem;
  margin-bottom: 2rem;
  font-weight: 300;
  font-size: 1.7rem;
  font-family: "Palatino Linotype", "Book Antiqua", "Palatino", serif;
  font-weight: bold;
}
  .h62{
  margin-top: 2rem;
  margin-bottom: 2rem;
  font-weight: 300;
  font-size: 2.5rem;
  font-family: "Palatino Linotype", "Book Antiqua", "Palatino", serif;
  font-weight: bold;
}
h5{
margin-top: 0rem;
  font-weight: 300;
  font-size: 1.5rem;
  font-family: "Palatino Linotype", "Book Antiqua", "Palatino", serif;
  font-weight: bold;

}
.h5{
margin-top: 0rem;
  font-weight: 300;
  font-size: 1.5rem;
  font-family: "Palatino Linotype", "Book Antiqua", "Palatino", serif;
  font-weight: bold;

}
h4{
  margin-left: 0.5rem;
  font-size: 1.5rem;
  font-family: "Palatino Linotype", "Book Antiqua", "Palatino", serif;
  font-weight: bold;

}
.img{
  width:400px;
  height:250px;
  margin-left:10px;
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);

}
.title{
  background-color: #000000;
  height: 35px;
  margin-left: 0rem;
  font-size: 2rem;
  font-family: "Palatino Linotype", "Book Antiqua", "Palatino", serif;
  font-weight: bold;
  color:#FFFFFF;
  background-color: #000000;
  padding: 5px;
}
  textarea {
    /* margin:0px 0px; this is redundant anyways since its specified below*/
    padding-top:10px;
    padding-bottom:25px; /* increased! */
    /* height:16px; */
    /* line-height:16px; */
    width:100%; /* changed from 96 to 100% */
    display:block;
    /* margin:0px auto; not needed since i have width 100% now */
  }
</style>



<script>
  function expandTextarea() {
      document.getElementById('content-form').addEventListener('keyup', function() {
          this.style.overflow = 'hidden';
          this.style.height = 0;
          this.style.height = this.scrollHeight + 'px';
      }, false);
  }
  expandTextarea();

  function initialize() {
    $('.category-btn').click(function() {
      $(this).css("background-color", '#5cb85c');
      $(this).css("border-color", '#5cb85c');
      $(this).css("color", 'white');
      $(this).siblings().css("background-color", 'grey');
      $(this).siblings().css("border-color", 'grey');
      $('input[name="post[category_id]"]').val($(this).attr('id'));
    });
  }
  initialize()

  $(".submit-btn").on('click', function(e) {
    $('#exampleModal').delay(2000).modal('hide')
  });

  $('#exampleModal').on('hidden.bs.modal', function (e) {
    $.ajax({
        type: 'GET',
        url: "/categories/1",
        datatype: "json",
        success: function (data) {
          if (data.id != $('.category-btn').last().attr('id')) {
            var $new_btn = $("<a>", {id: data.id, "class": "btn btn-success category-btn", html: data.name});
            $new_btn.css("margin-left", "4px")
            $('.category-list').append($new_btn)
            initialize()
          }
          else {
            assert('repetitive name!')
          }
          console.log(data.name)
        }
    });
  })
  $('.file-upload').on('change', function readURL(e) {
    if (this.files && this.files[0]) {
      var reader = new FileReader();

      reader.onload = function (e) {
        if ($(".img-preview").length == 0) {
          var $img = $("<img>", {src: e.target.result, "class": "img-preview"})
          $(".img-div").append($img)
        }
        else {
          $(".img-preview").attr('src', e.target.result)
        }
      };

      reader.readAsDataURL(this.files[0]);
    }
  })
</script>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', :back %>

app/views/posts/index.html.erb
<ol class="breadcrumb">
  <li><a class="h5">Platform</a></li>
  <li class="active">Posts</li>
  <% if request.query_parameters.present? %>
    <li class="active h5">Search results</li>
  <% end %>
</ol>
<div align="right"><%= link_to 'New Post', new_post_path, class: "btn btn-primary h5" %></div>

<% flash.each do |key, value| %>
  <div class="flash h5 <%= flash_class(key) %>">
      <%= value %>
  </div>
<% end %>

<div class="row search-banner">
  <div class="col-lg-5 ">
    <%= form_with url: "/posts", method: 'get', local: true do |form| %>
      <div class="input-group h5">
        <%= form.text_field :query, class: "form-control", placeholder: "Search for..." %>
        <span class="input-group-btn">
          <%= form.button :submit, class: "btn btn-default"%>
        </span>
      </div>
    <% end %>
  </div>
</div>

<% if @posts.count == 0 %>
  <div class="panel panel-danger">
    <div class="panel-heading h5">
      <h3 class="panel-title h5">No Post Can be Found, Sorry...</h3>
    </div>
    <div class="panel-body h5">
      <p>Based on your query, there's no related post in our system.</p>
    </div>
  </div>
<% else %>
  <% @posts.each do |post| %>
    <div class="image-flip" ontouchstart="this.classList.toggle('hover');">
      <div class="mainflip">
        <div class="frontside">
          <div class="card" style="width:114rem;">
            <h3 class="title">
              <%= post.caption %></h3>
              <br>
          <img class= "img fluid" src="http://www.gobeyondthebrochure.com/wp-content/uploads/2015/10/A-Wavering-Sense-of-Safety-at-University-of-California-Berkeley.jpg">
            <div class="card-body">
              <% if post.category.present? %>
                <%= link_to posts_path(category: post.category.id) do %>
                  <span class="label label-danger category-label">
                    <h4><%= post.category.name %></h4>
                  </span>
                <% end %>
              <% end %>
              <i class="pull-right card-body h5"> Last updated at <%= time_ago_in_words(post.updated_at, include_seconds: true) %> ago</i>
              <p class="margin h6"><%= post.content.lines.first %></p>
      </div>
      </div>
      </div>
      <br>
      <div class="backside">
      <div class="card" style="width:114rem;">
      <div>
       <% post.content.lines.each do |line| %>
      <p class="margin h6"><%= line %></p>
      <% end %>
      </div>
        <% if user_signed_in? %>
          <% if post.user == current_user %>
             <%= link_to 'Show', post, class: "btn btn-info margin h5" %>
            <%= link_to 'Edit', edit_post_path(post), class: "btn btn-success margin h5" %>
            <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure you want to delete?' }, class: "btn btn-danger h5"%>
          <% end %>
          <% if is_followed(current_user, post.user) %>
            <%= link_to 'Unfollow', unfollow_path(post.user_id), class: "btn btn-dark margin h5", method: :delete, remote: true %>
          <% else %>
            <%= link_to 'Follow User', follow_path(post.user_id), class: "btn btn-warning margin h5", method: :patch, remote: true %>
          <% end %>
        <% end %>
        <% if is_added(post, current_user) %>
          <%= link_to 'Remove from Dashboard', unadds_path(post.id), method: :delete, class: "btn btn-dark h5", remote: true %>
        <% else %>
          <%= link_to 'Add to Dashboard', adds_path(post), method: :patch, class: "btn btn-info h5", remote: true %>
        <% end %>
     </div>
</div>
</div>
</div>
  <% end %>
<% end %>

<%= paginate @posts %>



<style>

.margin {
  margin-top: 10px;
  margin-bottom:10px;
  margin-left: 10px;
  margin-right: 10px;
}
.search-banner {
  margin-bottom: 13px
}
.btn-dark {
  background-color: #394d5f;
  border-color: #394d5f;
  color: white;
}
.image-flip:hover .backside, .image-flip.hover .backside {
-webkit-transform: rotateY(0deg);
-moz-transform: rotateY(0deg);
-o-transform: rotateY(0deg);
-ms-transform: rotateY(0deg);
transform: rotateY(0deg);
}
 
.image-flip:hover .frontside, .image-flip.hover .frontside {
-webkit-transform: rotateY(180deg);
-moz-transform: rotateY(180deg);
-o-transform: rotateY(180deg);
transform: rotateY(180deg);
}
 
.image-flip {
margin-bottom:200px;
width: 300px;
height: 250px;
}
 
.mainflip {
-webkit-transition: 1s;
-webkit-transform-style: preserve-3d;
-ms-transition: 1s;
-moz-transition: 1s;
-moz-transform: perspective(1000px);
-moz-transform-style: preserve-3d;
-ms-transform-style: preserve-3d;
transition: 1s;
transform-style: preserve-3d;
position: relative;
}
 
.frontside, .backside {
-webkit-backface-visibility: hidden;
-moz-backface-visibility: hidden;
-ms-backface-visibility: hidden;
backface-visibility: hidden;
-webkit-transition: 1s;
-webkit-transform-style: preserve-3d;
-moz-transition: 1s;
-moz-transform-style: preserve-3d;
-o-transition: 1s;
-o-transform-style: preserve-3d;
-ms-transition: 1s;
-ms-transform-style: preserve-3d;
transition: 1s;
transform-style: preserve-3d;
position: absolute;
top: 0;
left: 0;
}
 
.frontside {
-webkit-transform: rotateY(0deg);
-ms-transform: rotateY(0deg);
z-index: 2;
}
 
.backside {
background: white;
-webkit-transform: rotateY(-180deg);
-moz-transform: rotateY(-180deg);
-o-transform: rotateY(-180deg);
-ms-transform: rotateY(-180deg);
transform: rotateY(-180deg);
}
 
.card, .card-img-top {
margin-bottom: 200rem;
border-width: 100%;
border-color: #000000;
background-image: url("https://wallpapertag.com/wallpaper/full/8/0/9/127761-download-free-light-yellow-background-1920x1080-for-iphone-6.jpg");
box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);

}
.card-title {
  background-color: #000000;
}
.h6{
  margin-top: 2rem;
  margin-bottom: 2rem;
  font-weight: 300;
  font-size: 1.7rem;
  font-family: "Palatino Linotype", "Book Antiqua", "Palatino", serif;
  font-weight: bold;
}
h5{
margin-top: 0rem;
  font-weight: 300;
  font-size: 1.5rem;
  font-family: "Palatino Linotype", "Book Antiqua", "Palatino", serif;
  font-weight: bold;

}
.h5{
margin-top: 0rem;
  font-weight: 300;
  font-size: 1.5rem;
  font-family: "Palatino Linotype", "Book Antiqua", "Palatino", serif;
  font-weight: bold;

}
h4{
  margin-left: 0.5rem;
  font-size: 1.5rem;
  font-family: "Palatino Linotype", "Book Antiqua", "Palatino", serif;
  font-weight: bold;

}
.img{
  width:400px;
  height:250px;
  margin-left:10px;
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);

}
.title{
  background-color: #000000;
  height: 35px;
  margin-left: 0rem;
  font-size: 2rem;
  font-family: "Palatino Linotype", "Book Antiqua", "Palatino", serif;
  font-weight: bold;
  color:#FFFFFF;
  background-color: #000000;
  padding: 5px;
}
</style>

<script>
$(function() {
  setTimeout(function(){
    $('.flash').slideUp(500);
  }, 1000);
});
</script>

app/views/posts/new.html.erb
<ol class="breadcrumb">
  <li><a class="h5">Platform</a></li>
  <li><%= link_to 'Posts', root_path%></li>
  <li class="active h5">New Post</li>
</ol>

<h1 class="h62">New Post</h1>

<%= render 'form', post: @post %>

<style>
 .h62{
  margin-top: 2rem;
  margin-bottom: 2rem;
  font-weight: 300;
  font-size: 2.5rem;
  font-family: "Palatino Linotype", "Book Antiqua", "Palatino", serif;
  font-weight: bold;
}

.h5{
margin-top: 0rem;
  font-weight: 300;
  font-size: 1.5rem;
  font-family: "Palatino Linotype", "Book Antiqua", "Palatino", serif;
  font-weight: bold;

}
</style>

app/views/posts/show.html.erb
<ol class="breadcrumb">
  <li><a>Platform</a></li>
  <li><%= link_to 'Posts', root_path %></li>
  <li class="active">No.<%= @post.id %></li>
</ol>

<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">
      <%= @post.caption %>
      <% if @post.category.present? %>
        <%= link_to posts_path(category: @post.category.id) do %>
          <span class="label label-danger category-label">
            <%= @post.category.name %>
          </span>
        <% end %>
      <% end %>
    </h3>
  </div>
  <div class="panel-body">
    <% @post.content.lines.each do |line| %>
      <p><%= line %></p>
    <% end %>

    <% if not @post.image.attachment.nil? %>
      <%= image_tag @post.image, style: 'max-width: 500px' %>
    <% end %>

    <br>
    

    <% if @post.user == current_user %>
      <%= link_to 'Edit', edit_post_path(@post) %> |
    <% end %>
    <%= link_to 'Back', :back %>
  </div>
</div>