config/routes.rb
Rails.application.routes.draw do
    #get 'welcome/index'
  devise_for :users
  #root :to => 'posts#index'
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # the followed are routes for the user_controller
  get "all_users", to: "users#all_users", as: "all_users"
  patch "/users/:id/like", to: "users#follow", as: "follow"
  #get "/users/:id/dashboard", to: "users#dashboard", as: "user_dashboard"
  patch "/posts/:id/adds", to: "posts#adds", as: "adds"
  post "/posts/add_category", to: "posts#add_category", as: "add_category"
  delete "/users/:id/unadds", to: "users#unadds", as: "unadds"
  delete "/users/:id/unlike", to: "users#unfollow", as: "unfollow"
  get "/users/:id/dashboard", to: "users#dashboard", as: "user_dashboard"
  get "/users/:id/profile", to: "users#profile", as: "user_profile"

  # the routes for category_controller
  get "/categories", to: "categories#index", as: "categories"
  get "/categories/:id", to: "categories#show", as: "category"
  post "/categories", to: "categories#create", as: "create_category"
  patch "/category/:id", to: "categories#update", as: "update_category"
  delete "/category/:id", to: "categories#destroy", as: "destroy_category"


  root :to => 'welcome#index'
end

app/views/layouts/_navbar.html.erb
<% if user_signed_in? %>
<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to root_path, class: "navbar-brand" do %><h6>
        Home</h6>
      <% end %>
    </div>
    <div class="navbar-header">
      <%= link_to posts_path, class: "navbar-brand" do %>
        <h6>Wall</h6>      
    <% end %>
    </div>
    <div class="navbar-header">
      <%= link_to all_users_path, class: "navbar-brand" do %>
        <h6>My Co-members</h6>
      <% end %>
    </div>
      <div class="navbar-header">
      <%= link_to categories_path, class: "navbar-brand" do %>
        <h6>Categories of Posts</h6>
      <% end %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
          <div class="btn-group navbar-btn">
            <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               <h5> <%= current_user.name %> </h5>
            </button>
            <ul class="dropdown-menu">
              <h4><li><%= link_to '  My Followers', all_users_path(followed: current_user.id) %></li></h4>
              <h4><li><%= link_to '  My Posts', posts_path(user_id: current_user.id) %></li></h4>
              <h4><li><%= link_to '  My Categories', categories_path(user_id: current_user.id) %></li></h4>
              <h4><li><%= link_to '  My Dashboard', user_dashboard_path(id: current_user.id) %></li></h4>
              <h4><li role="separator" class="divider"></li></h4>
              <h4><li><%= link_to '  Log out', destroy_user_session_path, method: :delete %></li></h4>
              <h4><li><%= link_to 'My Profile', user_profile_path(id: current_user.id) %></li></h4>
            </ul>
          </div>
  <% else %>
          <div align="right"><h6><%= link_to 'Sign in', new_user_session_path, class: "btn btn-primary navbar-btn" %></h6></div>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<style>
.navbar-default {
  background-color: #21618C;
}
.navbar-default .navbar-brand {
  color: white;
}
.navbar-btn {
  margin-top: 7px;
  margin-right: 15px;
}
h6{
  margin-top: 0rem;
  font-weight: 300;
  font-size: 2.5rem;
  font-family: "Palatino Linotype", "Book Antiqua", "Palatino", serif;
  font-weight: bold;
}
h5{
margin-top: 0rem;
  font-weight: 300;
  font-size: 1.5rem;
  font-family: "Palatino Linotype", "Book Antiqua", "Palatino", serif;
  font-weight: bold;

}
.h5{
margin-top: 0rem;
  font-weight: 300;
  font-size: 1.5rem;
  font-family: "Palatino Linotype", "Book Antiqua", "Palatino", serif;
  font-weight: bold;

}
h4{
  margin-left: 0.5rem;
  font-size: 1.5rem;
  font-family: "Palatino Linotype", "Book Antiqua", "Palatino", serif;
  font-weight: bold;

}
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clubs Communication System </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= render partial: "layouts/navbar" %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>